-- FinanceClinics Seed Data
-- Run after schema.sql

USE financeclinics;

-- =============================================
-- Default Admin User
-- Password: Admin@123 (change immediately in production!)
-- =============================================
INSERT INTO users (email, password_hash, name, role, is_active) VALUES
('admin@financeclinics.com', 'scrypt:32768:8:1$wOqVXR8D9e0PqYJL$9f3c8e0d1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b', 'Admin User', 'admin', TRUE);

-- =============================================
-- Pages
-- =============================================
INSERT INTO pages (title, slug, content, meta_title, meta_description, is_published, sort_order, template) VALUES
('Home', 'home', '<h2>Welcome to FinanceClinics</h2><p>Expert financial advisory services for healthcare providers. We specialize in fundraising, cost optimization, MIS & Data Analysis, and financial process implementation.</p>', 'FinanceClinics - Financial Advisory for Healthcare Providers', 'Expert financial advisory services specializing in fundraising, cost optimization, MIS/Data Analysis, and financial planning for healthcare organizations.', TRUE, 1, 'home'),
('About Us', 'about', '<h2>About FinanceClinics</h2><p>FinanceClinics is a premier financial advisory firm dedicated to serving healthcare providers. Our team of experienced professionals understands the unique financial challenges faced by hospitals, clinics, and healthcare organizations.</p><h3>Our Mission</h3><p>To empower healthcare providers with strategic financial solutions that enable them to focus on what matters most - patient care.</p><h3>Our Values</h3><ul><li><strong>Integrity:</strong> We uphold the highest ethical standards</li><li><strong>Excellence:</strong> We deliver exceptional results</li><li><strong>Partnership:</strong> We work alongside our clients as trusted advisors</li><li><strong>Innovation:</strong> We leverage cutting-edge financial strategies</li></ul>', 'About FinanceClinics - Healthcare Financial Advisory Experts', 'Learn about FinanceClinics, our mission, values, and commitment to providing exceptional financial advisory services to healthcare providers.', TRUE, 2, 'default'),
('Contact', 'contact', '<h2>Get in Touch</h2><p>Ready to optimize your healthcare organization''s financial performance? Contact us today for a free consultation.</p>', 'Contact FinanceClinics - Schedule a Consultation', 'Contact FinanceClinics for expert financial advisory services. Schedule a free consultation with our healthcare finance specialists.', TRUE, 3, 'contact');

-- =============================================
-- Services
-- =============================================
INSERT INTO services (title, slug, short_description, description, icon, features, meta_title, meta_description, is_featured, is_published, sort_order) VALUES
('Fundraising & Capital Advisory', 'fundraising', 'Strategic capital raising solutions tailored for healthcare organizations. We help you secure funding through diverse channels.', '<h2>Fundraising & Capital Advisory Services</h2><p>In the competitive healthcare landscape, securing adequate funding is crucial for growth and sustainability. Our fundraising services help healthcare organizations navigate the complex world of capital raising.</p><h3>What We Offer</h3><p>Our comprehensive fundraising support includes:</p><ul><li>Equity fundraising strategy development</li><li>Investor identification and outreach</li><li>Pitch deck and presentation preparation</li><li>Due diligence support</li><li>Term sheet negotiation</li><li>Deal structuring and closing</li></ul><h3>Why Choose Us</h3><p>With deep expertise in healthcare finance, we understand what investors look for in healthcare ventures. Our track record includes successful fundraises ranging from seed rounds to growth equity.</p>', 'chart-line', '["Equity & debt fundraising", "Investor relations", "Pitch preparation", "Due diligence support", "Deal structuring", "Valuation advisory"]', 'Fundraising Services for Healthcare - FinanceClinics', 'Expert fundraising and capital advisory services for healthcare providers. Secure funding through strategic investor relations and deal structuring.', TRUE, TRUE, 1),
('Cost Optimization', 'cost-optimization', 'Identify inefficiencies and implement cost-saving measures without compromising patient care quality.', '<h2>Cost Optimization for Healthcare</h2><p>Healthcare organizations face constant pressure to reduce costs while maintaining or improving quality of care. Our cost optimization services help you achieve this balance.</p><h3>Our Approach</h3><p>We conduct a comprehensive analysis of your operations to identify:</p><ul><li>Operational inefficiencies</li><li>Procurement optimization opportunities</li><li>Workforce optimization potential</li><li>Technology and automation opportunities</li><li>Revenue cycle improvements</li></ul><h3>Results You Can Expect</h3><p>Our clients typically achieve 15-30% cost reduction in targeted areas while improving operational efficiency and maintaining care quality.</p>', 'scissors', '["Operational efficiency audits", "Procurement optimization", "Workforce planning", "Process automation", "Revenue cycle improvement", "Vendor management"]', 'Healthcare Cost Optimization - FinanceClinics', 'Reduce healthcare operational costs without compromising quality. Expert cost optimization consulting for hospitals and clinics.', TRUE, TRUE, 2),
('MIS & Data Analysis', 'mis-data-analysis', 'Management Information Systems setup and advanced data analytics to drive informed decision-making.', '<h2>MIS & Data Analysis Services</h2><p>In today''s data-driven healthcare environment, having the right information at the right time is critical. Our MIS & Data Analysis services help you harness the power of your data.</p><h3>Services Include</h3><ul><li>MIS system design and implementation</li><li>Dashboard development and visualization</li><li>KPI definition and tracking</li><li>Predictive analytics</li><li>Financial reporting automation</li><li>Data governance frameworks</li></ul><h3>Benefits</h3><p>Transform your data into actionable insights that drive better clinical and financial outcomes.</p>', 'database', '["MIS implementation", "Dashboard development", "KPI tracking", "Predictive analytics", "Report automation", "Data governance"]', 'Healthcare MIS & Data Analysis - FinanceClinics', 'Transform healthcare data into actionable insights. Expert MIS implementation and data analytics services for healthcare organizations.', TRUE, TRUE, 3),
('Accounting & Auditing', 'accounting-auditing', 'Comprehensive accounting services and thorough auditing to ensure financial accuracy and compliance.', '<h2>Accounting & Auditing Services</h2><p>Accurate financial records and compliance are fundamental to healthcare organizations. Our accounting and auditing services ensure your finances are in order.</p><h3>Our Services</h3><ul><li>Financial accounting and bookkeeping</li><li>Internal audit services</li><li>Statutory compliance</li><li>Tax planning and filing</li><li>Financial statement preparation</li><li>Regulatory reporting</li></ul><h3>Healthcare Expertise</h3><p>Our team understands healthcare-specific accounting standards and regulatory requirements, ensuring compliance while optimizing your tax position.</p>', 'calculator', '["Financial accounting", "Internal audits", "Statutory compliance", "Tax planning", "Financial statements", "Regulatory reporting"]', 'Healthcare Accounting & Auditing - FinanceClinics', 'Professional accounting and auditing services for healthcare providers. Ensure financial accuracy and regulatory compliance.', TRUE, TRUE, 4),
('Process Implementation', 'process-implementation', 'Streamline financial workflows, implement best practices, and automate processes for maximum efficiency.', '<h2>Financial Process Implementation</h2><p>Efficient financial processes are the backbone of successful healthcare organizations. We help you design and implement processes that work.</p><h3>What We Do</h3><ul><li>Process mapping and optimization</li><li>Financial workflow design</li><li>ERP/software implementation support</li><li>Internal controls development</li><li>Standard operating procedures</li><li>Change management support</li></ul><h3>Our Methodology</h3><p>We follow a structured approach: assess current state, design future state, implement changes, and provide ongoing support to ensure adoption.</p>', 'cogs', '["Process optimization", "Workflow design", "ERP implementation", "Internal controls", "SOPs development", "Change management"]', 'Healthcare Financial Process Implementation - FinanceClinics', 'Implement efficient financial processes in your healthcare organization. Expert process design, automation, and change management.', TRUE, TRUE, 5);

-- =============================================
-- Blog Posts
-- =============================================
INSERT INTO blog_posts (title, slug, excerpt, content, category, tags, is_published, published_at, author_id) VALUES
('5 Key Financial Metrics Every Healthcare Administrator Should Track', '5-key-financial-metrics-healthcare', 'Understanding financial metrics is crucial for healthcare administrators. Here are the five most important metrics you should be monitoring.', '<h2>5 Key Financial Metrics Every Healthcare Administrator Should Track</h2><p>In the complex world of healthcare finance, staying on top of key performance indicators is essential for organizational success.</p><h3>1. Operating Margin</h3><p>Operating margin measures the profitability of your core operations. For healthcare organizations, a healthy operating margin typically ranges from 2-4%.</p><h3>2. Days in Accounts Receivable</h3><p>This metric indicates how quickly you''re collecting payments. The industry benchmark is 40-50 days.</p><h3>3. Cost per Patient Day</h3><p>Understanding your cost per patient day helps identify efficiency opportunities and benchmark against peers.</p><h3>4. Bad Debt Ratio</h3><p>Monitor the percentage of patient revenue that becomes uncollectible. Keep this below 3-4%.</p><h3>5. Cash Flow from Operations</h3><p>Positive cash flow ensures you can meet obligations and invest in growth.</p><h3>Conclusion</h3><p>Regular monitoring of these metrics will help you make data-driven decisions for your healthcare organization.</p>', 'Finance', '["financial metrics", "healthcare finance", "KPIs", "hospital management"]', TRUE, NOW(), 1),
('How to Prepare Your Healthcare Startup for Series A Funding', 'prepare-healthcare-startup-series-a', 'Raising Series A funding requires thorough preparation. Learn the key steps to make your healthcare startup investor-ready.', '<h2>How to Prepare Your Healthcare Startup for Series A Funding</h2><p>Transitioning from seed to Series A is a critical milestone for healthcare startups. Here''s how to prepare.</p><h3>Build a Strong Foundation</h3><ul><li>Demonstrate product-market fit</li><li>Show consistent revenue growth</li><li>Build a strong management team</li></ul><h3>Financial Preparation</h3><p>Investors will scrutinize your financials. Ensure you have:</p><ul><li>Clean, audited financial statements</li><li>Clear unit economics</li><li>Realistic financial projections</li><li>Understanding of your burn rate</li></ul><h3>Craft Your Story</h3><p>Your pitch should clearly articulate the problem, solution, market opportunity, and why your team is best positioned to win.</p><h3>Due Diligence Ready</h3><p>Organize all legal, financial, and operational documents in a virtual data room.</p>', 'Fundraising', '["Series A", "startup funding", "healthcare startup", "venture capital"]', TRUE, NOW() - INTERVAL 3 DAY, 1),
('Cost Reduction Strategies That Don''t Compromise Patient Care', 'cost-reduction-strategies-patient-care', 'Learn how to implement effective cost reduction strategies while maintaining the quality of patient care.', '<h2>Cost Reduction Strategies That Don''t Compromise Patient Care</h2><p>The challenge in healthcare cost reduction is maintaining quality while improving efficiency. Here are strategies that work.</p><h3>Supply Chain Optimization</h3><p>Negotiate better contracts, standardize supplies, and implement inventory management systems.</p><h3>Technology Investment</h3><p>While counterintuitive, strategic technology investments can reduce long-term costs through automation and efficiency.</p><h3>Workforce Optimization</h3><p>Optimize staffing ratios based on patient acuity and implement flexible scheduling.</p><h3>Preventive Care Focus</h3><p>Investing in preventive care reduces costly emergency interventions.</p><h3>Revenue Cycle Management</h3><p>Improving billing accuracy and collection processes can significantly impact the bottom line.</p>', 'Operations', '["cost reduction", "healthcare efficiency", "patient care", "hospital operations"]', TRUE, NOW() - INTERVAL 7 DAY, 1);

-- =============================================
-- Site Settings
-- =============================================
INSERT INTO settings (`key`, value, type, category, description) VALUES
('site_name', 'FinanceClinics', 'string', 'general', 'Website name'),
('site_tagline', 'Financial Advisory for Healthcare Providers', 'string', 'general', 'Website tagline'),
('site_description', 'Expert financial advisory services specializing in fundraising, cost optimization, MIS/Data Analysis, and financial process optimization for healthcare organizations.', 'string', 'general', 'Website meta description'),
('contact_email', 'contact@financeclinics.com', 'string', 'contact', 'Primary contact email'),
('contact_phone', '+1 (555) 123-4567', 'string', 'contact', 'Primary contact phone'),
('contact_address', '123 Finance Street, Healthcare District, NY 10001', 'string', 'contact', 'Office address'),
('social_facebook', 'https://facebook.com/financeclinics', 'string', 'social', 'Facebook page URL'),
('social_twitter', 'https://twitter.com/financeclinics', 'string', 'social', 'Twitter profile URL'),
('social_linkedin', 'https://linkedin.com/company/financeclinics', 'string', 'social', 'LinkedIn company URL'),
('footer_text', '© 2024 FinanceClinics. All rights reserved.', 'string', 'general', 'Footer copyright text'),
('google_analytics_id', '', 'string', 'analytics', 'Google Analytics tracking ID'),
('smtp_configured', 'false', 'boolean', 'email', 'Whether SMTP is configured');

-- =============================================
-- Sample Leads (for testing)
-- =============================================
INSERT INTO leads (name, email, phone, organization, message, preferred_contact_time, service_interest, status, privacy_accepted) VALUES
('Dr. John Smith', 'john.smith@cityhospital.com', '+1-555-0101', 'City General Hospital', 'We are looking for assistance with our upcoming fundraising round. We are a 200-bed hospital looking to expand our cardiac care unit. Please contact me to discuss how you can help.', 'Morning (9 AM - 12 PM)', 'Fundraising & Capital Advisory', 'new', TRUE),
('Sarah Johnson', 'sjohnson@healthclinic.org', '+1-555-0102', 'HealthFirst Clinics', 'Our clinic network has been struggling with cost management. We need help identifying areas for cost reduction without impacting patient care quality.', 'Afternoon (2 PM - 5 PM)', 'Cost Optimization', 'contacted', TRUE),
('Michael Chen', 'mchen@medicalgroup.com', '+1-555-0103', 'Premier Medical Group', 'We need to implement a new MIS system for better financial tracking and reporting. Can you help with system selection and implementation?', 'Flexible', 'MIS & Data Analysis', 'qualified', TRUE);

-- =============================================
-- Example MIS Template + Sample Data
-- =============================================
INSERT INTO mis_templates (name, columns, created_by, is_public) VALUES
('Basic Hospital MIS', '[{"key":"date","label":"Date"},{"key":"department","label":"Department"},{"key":"patient_count","label":"Patient Count"},{"key":"revenue","label":"Revenue"},{"key":"expenses","label":"Expenses"}]', 1, TRUE);

-- capture the inserted template id and use it for rows
SET @tpl_id = LAST_INSERT_ID();

INSERT INTO mis_data (template_id, data) VALUES
(@tpl_id, '{"date":"2025-11-01","department":"Cardiology","patient_count":45,"revenue":125000,"expenses":85000}'),
(@tpl_id, '{"date":"2025-11-01","department":"Orthopedics","patient_count":30,"revenue":90000,"expenses":60000}'),
(@tpl_id, '{"date":"2025-11-02","department":"Cardiology","patient_count":50,"revenue":140000,"expenses":92000}');
